// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/30/2025, 12:46:41 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/mxamu/OneDrive/Desktop/weather_app/weather_dashboard/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mxamu/OneDrive/Desktop/weather_app/weather_dashboard/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mxamu/OneDrive/Desktop/weather_app/weather_dashboard/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mxamu/OneDrive/Desktop/weather_app/weather_dashboard/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mxamu/OneDrive/Desktop/weather_app/weather_dashboard/plugins/**/*.{js,ts,mjs}","C:/Users/mxamu/OneDrive/Desktop/weather_app/weather_dashboard/composables/**/*.{js,ts,mjs}","C:/Users/mxamu/OneDrive/Desktop/weather_app/weather_dashboard/utils/**/*.{js,ts,mjs}","C:/Users/mxamu/OneDrive/Desktop/weather_app/weather_dashboard/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mxamu/OneDrive/Desktop/weather_app/weather_dashboard/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mxamu/OneDrive/Desktop/weather_app/weather_dashboard/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/mxamu/OneDrive/Desktop/weather_app/weather_dashboard/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;